### ISSUE TITLE
Witch Cauldron causes server to crash

### ISSUE THREAD

**Issue by LucynyTheWitch** [Polarice3/Goety-2#11]
Placing the cauldron crashes the server, yet after reopening the server it stays where it was placed, and interacting, or breaking it crashes the server and doesn't break it. Standing on it, places the player into an infinite loop of being disconnected from the server.

**Comment by Polarice3** [comment]
Can you provide any Crash report or Server Logs?

**Comment by Polarice3** [comment]
I did a test on my Server and everything seems to work properly. Do you have any other mods added in? Are you using the latest version of Goety?

**Comment by Polarice3** [comment]
Close for now due to lack of information.
