### ISSUE TITLE
Skull Lord related crash.

### ISSUE THREAD

**Issue by AndrewMods1** [Polarice3/Goety-2#12]
Had the Skull Lord fight the Haunted Armor and the game crashed. 
[crash-2023-07-15_16.42.39-server.txt](https://github.com/Polarice3/Goety-2/files/12060805/crash-2023-07-15_16.42.39-server.txt)

**Comment by Polarice3** [comment]
No idea how this crash can happen. I'll see what I can do, please inform me if the problem remains in future updates.
