### ISSUE TITLE
Server crashes when I activate Necroturgy RItual

### ISSUE THREAD

**Issue by EnricoVvV** [Polarice3/Goety-2#13]
Hi, my server crashes when I put the necrotic brazier on the black altar, is there a way to fix it?

Error: https://pastebin.com/ZyifqkbQ

**Comment by Polarice3** [comment]
The crash looks to be made by a Brewing Stand at this location: (-877,74,-7003). It appears to be using a faulty recipe to brew something. Otherwise, have no clue as to how the crash can happen as Rituals have no ties with Brewing.

**Comment by EnricoVvV** [comment]
My bad, sorry! I linked the wrong error 🥲

Video of the crash: https://imgur.com/a/ZqIvHpI
Error on console: https://pastebin.com/qE0zSC2R

**Comment by Polarice3** [comment]
Cool! Will be fixed in next update!

**Comment by EnricoVvV** [comment]
Ohhh okok, thank you! 😃

**Comment by EnricoVvV** [comment]
If it can help, I tried again and just placing the Necrotic Blazer anywhere is enough to crash the server.

**Comment by Polarice3** [comment]
Does the crash still happen in the latest update?

**Comment by EnricoVvV** [comment]
No, it works perfectly now, thank you so much! :D
