### ISSUE TITLE
Rituals invalidated by automation due to pedestals having a stack size over 1

### ISSUE THREAD

**Issue by Jackiecrazy** [Polarice3/Goety-2#14]
automation such as hoppers can insert a stack with a size greater than 1 into the pedestal (in my case it was my sortingwood engine, which was a lot harder to relocate). Doing so causes the ritual to fail after activation as it consumes one item, finds the remaining stack, and immediately aborts on the grounds of the ritual being invalid.

**Comment by Polarice3** [comment]
Got it! Will try to fix this! I increased the stack size to allow multiple ritual recipe outputs as the Dark Altar uses the same size as the pedestal.

**Comment by Polarice3** [comment]
This should be fixed in the latest updates.
