### ISSUE TITLE
Liches cannot be hit by mobs

### ISSUE THREAD

**Issue by Jackiecrazy** [Polarice3/Goety-2#15]
Mobs other than undead target me, but cannot deal damage. The hit animation does not play and I do not get knocked back. I suspect it has to do with [this line](https://github.com/Polarice3/Goety-2/blob/d00a006ab9750559cacf3c33e485b3868ebb0b32/src/main/java/com/Polarice3/Goety/common/events/LichEvents.java#L244) in conjunction with another mod that prevents damage on freshly spawned zombies, perhaps. I can confirm that it has to do with being a lich, but my profile has over 300 mods and I don't know which of the others could be possibly causing it.

**Comment by Polarice3** [comment]
I guess I could look into this. Perhaps provide a modlist as well.

**Comment by Jackiecrazy** [comment]
[text.txt](https://github.com/Polarice3/Goety-2/files/12708310/text.txt)
It's also happening with things that really should be attacking zombies, like iron golems. I'm also a little concerned that constantly generating a new zombie, even if it's not being spawned, may impact performance somewhat.

**Comment by Polarice3** [comment]
I see, alright, will look into this then!

**Comment by Jackiecrazy** [comment]
Between inexplicable crashing, datapack failures, dependency chains, and broken respawning, that was an extremely aggravating issue to test. Minecraft modding is really inaccessible nowadays. I guess it's the liberal use of mixins.
It's actually my own mod all along. Bizarre.

**Comment by Jackiecrazy** [comment]
aha, I see.
to add a pseudo-"attack speed" to mobs (especially slimes), I used a mechanic that temporarily disables attacking after every mob attack. With lichdom, all attacks are first directed to a dummy zombie, which procs the attack speed hack, which causes the actual player interaction to do nothing.
I'll try to fix it from my side, though my point about potential lag still stands.

**Comment by Polarice3** [comment]
I removed the potential lag thing in the latest update.
