### ISSUE TITLE
a way to turn off lich soul regeneration

### ISSUE THREAD

**Issue by Jackiecrazy** [Polarice3/Goety-2#16]
considering that fire resistance isn't a terribly difficult potion to brew and water bucket is usually an option, I'm finding lich healing quite powerful. This is exacerbated by the fact that some mods such as combat next or scaling health allow changing the minimum hunger level to regen. Lich sets your hunger to 17 constantly, which blocks healing in vanilla but still allows you to regenerate with these mods installed. One way I see to circumvent this would be to refill the hunger bar based off the soul bar (clear exhaustion per tick by deducting souls), though this may be a little excessive.

Something like what I suggested for [vampirism](https://github.com/TeamLapen/Vampirism/issues/1262) might work nicely, too.

**Comment by Polarice3** [comment]
You can increase the amount of Soul Energy needed to heal in the goety.toml config, under lichHealCost, to use a lot more Soul Energy to heal. The whole hunger thing sounds like other mod's problem.

**Comment by Polarice3** [comment]
Overall, this isn't an actual issue since it's based on modifications made by other mods and personal preference.

Maybe label it as enhancement next time.

**Comment by Polarice3** [comment]
The latest update added many configs to Lichdom, such as disabling Soul Energy regeneration, the time it takes to regen and how much health is regenerated!

Sorry if I seemed rude before, was feeling upset.
