### ISSUE TITLE
Mod crash on 1.20.1 server

### ISSUE THREAD

**Issue by oof100200** [Polarice3/Goety-2#19]
### Mod Loader

forge 47.1.3

### Mod version

goety2.5.1.1

### Issue description

having this problem on server start up, when i use 2.5.1.1 version of this mod, i seems cannot boots up my server, it doesn't happens when i use 2.5.0.0 it don't happens, can you please check on that?

### Link or Post Log Files

crash log:
https://link.jscdn.cn/1drv/aHR0cHM6Ly8xZHJ2Lm1zL3QvcyFBdHRfV09jMXBjUEZoUkNnNS1XZ053SllkdEl6P2U9bXdsQlpt.txt

**Comment by Polarice3** [comment]
Should be fixed in the latest update!
https://modrinth.com/mod/goety/version/2.5.1.2
https://legacy.curseforge.com/minecraft/mc-mods/goety/files/4833632
