### ISSUE TITLE
Focus bag keys don't work with totem in inventory

### ISSUE THREAD

**Issue by kyragit** [Polarice3/Goety-2#2]
The focus bag keybinds don't do anything if you have a Totem of Souls in your inventory. The cause is `com.Polarice3.Goety.utils.TotemFinder`, line 23. You're calling `isMatchingItem()` instead of `isFocusBag()`.

On an unrelated note, I'd just like to say that this mod is incredible! You definitely deserve more credit and downloads for this, it's genuinely one of the coolest magic mods I've seen for 1.19. Keep up the good work!

**Comment by Polarice3** [comment]
Good Catch! This and the Soul Energy issue will be fixed in next update! Thank you for pointing out the offending codes! Makes my life easier :)

**Comment by kyragit** [comment]
Thanks for fixing it!
