### ISSUE TITLE
necromancer crush

### ISSUE THREAD

**Issue by SAGA23456** [Polarice3/Goety-2#20]
### Mod Loader

1.20.1　1.44

### Mod version

2.5.1.2

### Issue description

It will crash if you have several Necromancers at the same time.

### Link or Post Log Files

[2023-11-03-9.log](https://github.com/Polarice3/Goety-2/files/13249120/2023-11-03-9.log)

### Steps to reproduce

Summon some necromancer-type mobs

**Comment by Polarice3** [comment]
Is this played on a Minecraft Server or singleplayer?

**Comment by Polarice3** [comment]
I think I figured out the problem! Should hopefully be fixed next update!
