### ISSUE TITLE
1.20.1 Crash from ravager

### ISSUE THREAD

**Issue by Syclusion** [Polarice3/Goety-2#21]
### Mod Loader

Forge 47.1.3

### Mod version

2.5.1.3

### Issue description

Summoning a goety ravager crashes game and keeps world from loading after the fact.

### Link or Post Log Files

https://pastebin.com/RiyfenQb

### Steps to reproduce

Open world

Summon ravager (via commands crashes too)

Crash

**Comment by Syclusion** [comment]
(You will see a lot of mods in the list, all are disabled except curios and goety. Just for clarity)

**Comment by Polarice3** [comment]
Thanks! Fixed this and other Ravager and server related bugs on the latest update!
