### ISSUE TITLE
Crash when using Growlight or Soullight

### ISSUE THREAD

**Issue by SAGA23456** [Polarice3/Goety-2#22]
### Mod Loader

1.20.1　2.1

### Mod version

2.5.1.2

### Issue description

Suddenly crashes when using Growlight or Soullight.

### Link or Post Log Files

grow light
[2023-11-05-1.log](https://github.com/Polarice3/Goety-2/files/13258894/2023-11-05-1.log)
soul light
[2023-11-05-2.log](https://github.com/Polarice3/Goety-2/files/13258904/2023-11-05-2.log)

**Comment by Polarice3** [comment]
Your logs doesn't tell me anything unfortunately.

Does the crash happens immediately when you cast the spells?

**Comment by SAGA23456** [comment]
No, the first shot works fine, but when I shoot the second shot it suddenly crashes

**Comment by Polarice3** [comment]
Thanks for letting me know! Also, fixed it on the latest update!
