### ISSUE TITLE
Crones are hostile even if you wear both the Witch/Crone Hat and Witch Robes.

### ISSUE THREAD

**Issue by SAGA23456** [Polarice3/Goety-2#24]
### Mod Loader

1.20.1　2.1

### Mod version

2.5.1.2

### Issue description

I wear both the Witch/Crone Hat and Witch Robes and try to make a deal, but the crone is hostile.

### Steps to reproduce

Wear both Witch/Crone Hat and Witch Robes

**Comment by Polarice3** [comment]
Oof! Sorry about that! Will be fixed next update!

**Comment by Polarice3** [comment]
Should be fixed as of Goety 2.5.1.5:
https://modrinth.com/mod/goety/version/2.5.1.5
