### ISSUE TITLE
I can't hear the music disc

### ISSUE THREAD

**Issue by SAGA23456** [Polarice3/Goety-2#25]
### Mod Loader

1.20.1　1.44

### Mod version

2.5.1.2

### Issue description

I can't hear anything when I put Apostol and the Chancellor's music disc in the jukebox.

**Comment by Polarice3** [comment]
It'll be fixed next update!

**Comment by Polarice3** [comment]
Should be fixed as of Goety 2.5.1.5:
https://modrinth.com/mod/goety/version/2.5.1.5
