### ISSUE TITLE
[Feature] Config option for the Fire Spawn Cage

### ISSUE THREAD

**Issue by SPYROHAWK** [Polarice3/Goety-2#29]
On the wiki, it says that this mod is highly configurable. I didn’t quite believe it until I looked at the configs. Wow, almost every single value in the mod can be adjusted with the configs. That’s amazing, I’m super impressed. Plus specific features like the Night Beacon enforcing eternal night or the Arca death save mechanic that people may not like can be turned on and off.

I’m making a custom pack for a group of friends and I’m including Goety, and the only feature that people have been concerned about is the ability to move mob spawners around. Okay, technically it’s not moving the spawner with the Fire Spawn Cage, it’s destroying it and making a new one, but it’s basically moving a spawner around.

I figured, sure, that’s fine, moving spawners around is one of those features that tends to be a bit controversial, that’s gonna have a config option. I’ll just disable it. But what do you know, it’s not there.

Unless I’m just blind or being an idiot, which is always an option, but I took a good look and couldn’t find it.

So… yeah. Sorry for the long backstory, but you get the point. It would be really nice to have a config option to disable the Fire Spawn Cage so you can’t move spawners around.

**Comment by SPYROHAWK** [comment]
Idk why this is labeled as “bug”, I guess GitHub just automatically does that. It’s not a bug. Just enhancement.

**Comment by Polarice3** [comment]
Sounds like a good idea! Will add in next update!

**Comment by Polarice3** [comment]
Fire Spawn Cages' functionality can now be disabled through goety.toml under "fireSpawnCage".
