### ISSUE TITLE
Using the Dark Scroll outside of a woodland mansion crashes the game

### ISSUE THREAD

**Issue by kyragit** [Polarice3/Goety-2#3]
Title. Crash report is `java.lang.IllegalStateException: Unable to calculate boundingbox without pieces`. Issue is `com.Polarice3.Goety.common.items.DarkScrollItem`, line 40. I'm not positive on this one, but I think using `getStructureWithPieceAt()` instead of `getStructureAt()` could fix it?

**Comment by Polarice3** [comment]
Fixed in latest update!
