### ISSUE TITLE
Server Side Crash on Most Recent Update

### ISSUE THREAD

**Issue by SlayDigger** [Polarice3/Goety-2#31]
### Mod Loader

Forge 47.2.1

### Mod version

Goety 2.5.4.0

### Issue description

Tried to update my modpack and worked fine on the client side, but when starting up on my server, was met with a crash.

### Link or Post Log Files

https://mcpaste.io/7924dffef9e0e24b

### Steps to reproduce

1. Launch Goety 2.5.4.0 for Forge 47.2.1 on a Dedicated Server
2. Check Logs ?

**Comment by Polarice3** [comment]
Will look into this!

**Comment by Polarice3** [comment]
Should be fixed as of [Goety 2.5.4.1](https://legacy.curseforge.com/minecraft/mc-mods/goety/files/4954449)
