### ISSUE TITLE
Crashing Tick Loop

### ISSUE THREAD

**Issue by ZanePearl** [Polarice3/Goety-2#33]
### Mod Loader

forge-36.2.34

### Mod version

Goety-1.36.1

### Issue description

Whenever using an Arca to save myself either as human or lich, the server will crash instantly, when using a empty cage and a fire cage to make a spawner the server will crash just the same, While using the teleport focus to an Arca will only disconnect me and the server is fine. 
I thought it could be a mod confliction so I tried recreating the events in a server with only Goety and it’s dependent mod curious. The crash happened again although unlike before I didn’t get a crash report. 
So far I’ve had to disable arca from saving you just to use it and I hope there’s a way to fix it.

### Link or Post Log Files

[message.txt](https://github.com/Polarice3/Goety-2/files/14165527/message.txt)

### Steps to reproduce

One, place an Arca down, Two: die as a human with enough soul enegery to be sent back, or as a lich just die, you will be sent to the Arca for a split frame before you get disconnect and the server crashes. For the fire cage I simply just right clicked a fire cage on a empty cage and it crashed.

### Additional information

I am using aternos. Aswell for the fact this happens with no other mods but Goety, only difference being is that with my modpack I get a crash report while with Goety alone I don’t, I also don’t have this issue in single player

**Comment by Polarice3** [comment]
Should be fixed as of latest update!
