### ISSUE TITLE
Soul Shield Amulet can't fly

### ISSUE THREAD

**Issue by EYW-015** [Polarice3/Goety-2#34]
### Mod Loader

forge-43.3.7

### Mod version

2.24.0 + 2.25.2

### Issue description

Soul Shield Amulet should make player can fly when over 50% HP, but it can't

### Additional information

2.24.0 can't fly, then I try to update to 2.25.2 still not work.
Create a new game that mod only contain Goety-2.25.2 and Curios-5.1.4.4 and not work.

**Comment by Polarice3** [comment]
Do you mean in Creative? Does the visual effect appear on you even if you have over 50% HP?
Also, was your maximum health increased? Were you using other mods?

**Comment by EYW-015** [comment]
@Polarice3 
Not Creative, it's survive mode.
Full HP.
There is no Visual effect.
No other mods, only Goety-2.25.2 and Curios-5.1.4.4

I've try to make a new gamepack with forge-43.3.7,
and add two mods above, do nothing else.

**Comment by Polarice3** [comment]
Wait, if you have no other mods, then how are you Creatively flying on Survival?

**Comment by EYW-015** [comment]
So that means "it will disable fly below 50% HP"
Not "provide fly over 50% HP"
Fly mode should be provided by other mods.

I've misunderstood.
