### ISSUE TITLE
Sculk Devourer and Warden interaction issues

### ISSUE THREAD

**Issue by nortonii** [Polarice3/Goety-2#37]
### Mod Loader

forge-43.3.7

### Mod version

Goety 2.24.0

### Issue description

After the Warden was killed by the minecart, I saw the Sculk Devourer animation, but it didn't seem to increase the correct amount of souls, and maybe not even any

### Steps to reproduce

Place rails on the soul sand and place 25 minecarts, surrounded by blocks, with a Radius Enchantment 1 Devourer on one side and below the soul sand. Subsequently, the Warden was made to fall in.

**Comment by Polarice3** [comment]
The amount of soul energy added by the Sculk Devourer depends on the mob's experience drop, similar to how Sculk is generated in vanilla.

**Comment by Polarice3** [comment]
The Warden drops 5 experience, so the amount of Soul Energy made by the Devourer would be 5 Soul Energy if the block's not enchanted with Soul Eater.
