### ISSUE TITLE
Goety lich rendering error when riding some creatures.

### ISSUE THREAD

**Issue by Spoofygamer** [Polarice3/Goety-2#39]
### Mod Loader

Forge 47.2.0

### Mod version

goety-2.5.12.4

### Issue description

Lich form renders double when riding certain creatures from Alex's Caves. I'm thinking its a problem with how AC renders the player model when mounting certain creatures so the player moves with the creatures animations.

EX: Tremorsaurus and Tremorzilla
![2024-04-11_13 47 25_3](https://github.com/Polarice3/Goety-2/assets/38812100/9899445c-7174-486a-9408-08d20e3324b4)
![2024-04-11_13 35 27_2](https://github.com/Polarice3/Goety-2/assets/38812100/14b3b249-1049-4e5b-b008-374b8414c1c1)
=

### Additional information

I've also posted a similar report on AC's GitHub.

**Comment by Polarice3** [comment]
Fixed as of Goety 2.32.0 and Goety 2.5.13.0!
![2024-04-12_23 19 40](https://github.com/Polarice3/Goety-2/assets/12710903/2f8eb33c-1bf3-4a40-9bc3-f1852144aac3)
