### ISSUE TITLE
how do I increase the limit for wilds monster summons?

### ISSUE THREAD

**Issue by UwUsheep** [Polarice3/Goety-2#40]
### Mod Loader

forge 47.2.20

### Mod version

1.20.1 2.5.13

### Issue description

So I am just asking but for some reason I try to make the whisperer with no servants I have the scroll and it says I am up to my limit so I am wondering how do you change the limit on wild monsters.

**Comment by Polarice3** [comment]
Accidentally made the conditions for Whisperer Mold method backwards, will fix this next update:
https://github.com/Polarice3/Goety-2/blob/5a03204272b1b6a65b257d9e46af64b2f25bb222/src/main/java/com/Polarice3/Goety/common/magic/construct/WhispererMold.java#L101

**Comment by UwUsheep** [comment]
ok thanks a lot!

**Comment by Polarice3** [comment]
https://github.com/Polarice3/Goety-2/blob/64e9057623dab27dded1db0a9d1bafe1650f1d2e/src/main/java/com/Polarice3/Goety/common/magic/construct/WhispererMold.java#L101
Fixed as of Goety 2.33.0 and 2.5.14.0!
