### ISSUE TITLE
Is Blighted Shack's generation probability a joke?

### ISSUE THREAD

**Issue by HonmaSakura** [Polarice3/Goety-2#41]
After searching for over four hours and not finding you Blighted Shack, if the probability of generation is not high come up with a way to locate it instead of letting players spend all their time running the map to boost their game time.

**Comment by Polarice3** [comment]
> Is Blighted Shack's generation probability a joke?

Yes 😈

Anyways, you can rarely get a map for the Blighted Shack by trading with Witches while wearing a Witch Robe and Hat or Warlock Robe. Also, the next update will deal with this issue.
