### ISSUE TITLE
Error recipe : soul_absorber_recipes

### ISSUE THREAD

**Issue by 2929762171** [Polarice3/Goety-2#42]
### Mod Loader

forge 43.3.7

### Mod version

Goety-2.35.5

### Issue description

Error parsing recipe goety:ethereal_spirit_souls[goety:soul_absorber_recipes]: {"type":"goety:soul_absorber_recipes","ingredient":{"item":"born_in_chaos_v1:ethereal_spirit"},"soulIncrease":5,"cookingtime":50}: com.google.gson.JsonSyntaxException: Unknown item 'born_in_chaos_v1:ethereal_spirit'

**Comment by Polarice3** [comment]
Will be fixed soon!

**Comment by Polarice3** [comment]
Fixed as of latest update
