### ISSUE TITLE
[Feature] Relationship between dark magic and the ancient city, and some discover of the past of the story

### ISSUE THREAD

**Issue by AnterCreeper** [Polarice3/Goety-2#43]
Maybe since a disaster of magic(maybe caused by witch because of banished(for study magic) from village), grand city covered with sculk(take away the soul of creatures, so have exp) (how the warden appeared?) and as the time passes by the city sunk into the ground.(And the illager(the descendant of faithful believer))

**Comment by Polarice3** [comment]
Okay?

**Comment by AnterCreeper** [comment]
> Okay?

Really appreciate your work.🥹 Not break the origin vanilla story & art & definition, and expand the content. (In contrast the mojang update nothing. 😭😭😭)

**Comment by SpiritTreeFromBetweenlands** [comment]
What you just wrote? That do not make any sense.
