### ISSUE TITLE
Structure generated not properly

### ISSUE THREAD

**Issue by AnterCreeper** [Polarice3/Goety-2#44]
### Mod Loader

1.19.2 Forge 43.4.0

### Mod version

2.35.1

### Issue description

The structure generated not correctly.(A giant floating object) Use "What structure is this" mod shows goety:crypt. 
Before:
![2024-08-01_17 11 20](https://github.com/user-attachments/assets/2b4a07a3-fc88-4c63-b29b-67031db7f3df)
After remove the mod:
![2024-08-01_17 38 16](https://github.com/user-attachments/assets/dbf213ca-7d4a-4fd5-8f50-d58628beea89)

However thing good while use /place command.
the mod Terralith applied. Seems cause by it.

**Comment by Polarice3** [comment]
Crypt structure generation has been changed from Goety 2.36.1 and up to not modify the surrounding/ground above.
