### ISSUE TITLE
NullPointerException With Zoglin

### ISSUE THREAD

**Issue by GopherLoaf** [Polarice3/Goety-2#46]
### Mod Loader

forge-47.3.0

### Mod version

Goety 2.5.18.0

### Issue description

When a zoglin becomes hostile towards an apostle it causes the game to crash whilst ticking entity due to "Error: java.lang.NullPointerException: Ticking entity."

### Link or Post Log Files

[crash-2024-08-06_18.39.59-server.txt](https://github.com/user-attachments/files/16516391/crash-2024-08-06_18.39.59-server.txt)
[latest.log](https://github.com/user-attachments/files/16516393/latest.log)

### Steps to reproduce

1. Create a new world
2. Spawn an apostle
3. Spawn a zoglin near the apostle

**Comment by Polarice3** [comment]
Good find! Will be fixed on the upcoming update!

**Comment by Polarice3** [comment]
Fixed as of Goety 2.5.19.0
