### ISSUE TITLE
Crash rendering first person gloves

### ISSUE THREAD

**Issue by ochotonida** [Polarice3/Goety-2#5]
Equipping a curio with a renderer not added by Goety in the glove slot crashes the game.
Fix is adding an instanceof check here:
https://github.com/Polarice3/Goety-2/blob/1154a59f09f86e5afa626d33e07ce8d760ca3865/src/main/java/com/Polarice3/Goety/client/render/WearRenderer.java#L37-L42

Crash report here: https://github.com/ochotonida/artifacts/issues/198

**Comment by Polarice3** [comment]
Thanks man! I've managed to find a way to fix this, so thanks for informing me! :) The fix will be in the next update.

**Comment by Polarice3** [comment]
Re-uploaded 2.0.4 to have crash fix.
