### ISSUE TITLE
[Feature] Prevent raiders from get entity cramming damage when spawns

### ISSUE THREAD

**Issue by lzm11111111** [Polarice3/Goety-2#50]
When I installed both the illager and spillager and goety mods, the raid bar was not full when the 4th wave and every subsequent wave spawned, the reason was that there were too many raiders and they were get entities cramming damage. There should be a way to fix this.

**Comment by Polarice3** [comment]
This isn't a unique issue towards Goety.

Use Hook Bell to teleport Raiders towards a specific location. Also use the gamerule "maxEntityCramming" to prevent entity cramming damage.
