### ISSUE TITLE
Freezing lamp block blockstate naming issue

### ISSUE THREAD

**Issue by Syclusion** [Polarice3/Goety-2#52]
### Mod Loader

NA

### Mod version

2.5.23.1

### Issue description

Freezing lamp block doesn't follow default naming conventions of lamps, even if it is inverted it should have and use a [lit=true] blockstate. E.G. furnaces, lamps, etc. Normally this would seem inconsequential but specifically this creates issues with shader / mod compatability that rely on blockstates to differentiate between the two states rather than using the default block ID.

**Comment by Polarice3** [comment]
Ok

**Comment by Polarice3** [comment]
Wait, I'm confused, what do you mean?
Freezing Lamp Blockstate:
{
  "variants": {
    "lit=true": { "model": "goety:block/freezing_lamp" },
    "lit=false": { "model": "goety:block/freezing_lamp_off" }
  }
}

Redstone Lamp Blockstate:
{
  "variants": {
    "lit=false": {
      "model": "minecraft:block/redstone_lamp"
    },
    "lit=true": {
      "model": "minecraft:block/redstone_lamp_on"
    }
  }
}

Why does your shaders look at the model file name instead of the blockstate name?

**Comment by Polarice3** [comment]
https://github.com/Polarice3/Goety-2/blob/1.20/src/main/resources/assets/goety/blockstates/freezing_lamp.json

**Comment by Syclusion** [comment]
Very strange, the lit=true blockstate is not being recognized when I f3+I or when I input it manually, let me do some more research into what's going on

**Comment by Syclusion** [comment]
You are correct, my apologies. I made an assumption that was wrong, it seems its an incompat with another mod that dedeuplicates blockstates
