### ISSUE TITLE
[1.20.1] Vanilla Villagers converting to Heretics on adding Goety mod

### ISSUE THREAD

**Issue by SodiumZH** [Polarice3/Goety-2#53]
I'm adding Goety on an existing save data. I had 3 Librarians and 1 unemployed Villager. After adding Goety (2.5.24.0) the 3 Librarians converted to Heretics and the unemployed Villager kept unchanged.

**Comment by Polarice3** [comment]
Set this to false: 
https://github.com/Polarice3/Goety-2/blob/1.20/src/main/java/com/Polarice3/Goety/config/MobsConfig.java#L523
