### ISSUE TITLE
There are lot of spamming message "Not a string" in the log

### ISSUE THREAD

**Issue by Git-Reternos** [Polarice3/Goety-2#54]
Mod Loader
Forge 47.3.11

Mod version
Goety 2.5.24.0

Modlist:
1.Better Combat
2.Cloth Config API
3.Goety
4.PlayerAnimator
5.Xenon

Link or Post Log Files
[latest.log](https://github.com/user-attachments/files/17486310/latest.log)

Additional information
No response

**Comment by Polarice3** [comment]
Not really an issue since it's purely log spam. Also not sure if it's from my mod instead of the others. Use a log filtering plugin and it'll be resolved for you.

**Comment by Git-Reternos** [comment]
I'm sure that spamming message "Not a string" coming from Goety
after i tested Goety only with Curios API
Ye i understand it's not really an issue there but kinda annoying for me when i was checking message info
Thanks for reply 
[latest.log](https://github.com/user-attachments/files/17487965/latest.log)

**Comment by Polarice3** [comment]
Might have to do with not having Patchouli installed.

**Comment by Git-Reternos** [comment]
[latest.log](https://github.com/user-attachments/files/17488188/latest.log)
After installed Patchouli it still pop up

**Comment by Polarice3** [comment]
Cannot replicate or find source of this issue sorry

**Comment by Git-Reternos** [comment]
oh i found that annoying messages disappear at latest version 
Thanks you
