### ISSUE TITLE
[Bug] Assertions are not enabled

### ISSUE THREAD

**Issue by JoshieGemFinder** [Polarice3/Goety-2#56]
Due to compatibility with versions earlier than Java 1.4, assertions are not enabled by default in Java, 

Because Goety makes use of the `assert` statement to ensure sidedness and in several of its packets, assertions being non-functional causes several severe security flaws; I recommend either enabling assertions programmatically or making use of a different function to ensure these assertions actually trigger.

**Comment by Polarice3** [comment]
Most assert statements have been removed on recent updates.
