### ISSUE TITLE
[crash]ClassCastException Error Causing Raid Crash

### ISSUE THREAD

**Issue by Kiiley** [Polarice3/Goety-2#57]
While using the Goety mod, a ClassCastException error occurs when triggering a raid event, resulting in the server crashing and when I set specialIllagerRaid = false in the config, the crash still occurs
Minecraft Version:  1.20.1
Goety Version: goety-2.5.25.0
Server Type: running on Arclight core and forge 47.3.11

crashlog:
[crash-2024-11-02_17.49.20-server.txt](https://github.com/user-attachments/files/17608049/crash-2024-11-02_17.49.20-server.txt)

**Comment by Polarice3** [comment]
Crash log has no indication that Goety is responsible for the crash. Have you tried making a Raid without Goety installed?

**Comment by Kiiley** [comment]
> Crash log has no indication that Goety is responsible for the crash. Have you tried making a Raid without Goety installed?

Sure I tried rebuilding Arclight in another folder and the mods only have goety and curious-api and the crash still happened
![image](https://github.com/user-attachments/assets/b8595543-4c20-43fe-973f-2edce1209d87)
![image](https://github.com/user-attachments/assets/73a24753-a075-433a-ad61-630a329d2159)

**Comment by Polarice3** [comment]
Might be caused by Arclight raid mixin conflicting with Goety: https://github.com/Polarice3/Goety-2/blob/1.20/src/main/java/com/Polarice3/Goety/mixin/RaidMixin.java

In which case, try disabling armoredRavagerRaid on config

**Comment by Kiiley** [comment]
> Might be caused by Arclight raid mixin conflicting with Goety: https://github.com/Polarice3/Goety-2/blob/1.20/src/main/java/com/Polarice3/Goety/mixin/RaidMixin.java
> 
> In which case, try disabling armoredRavagerRaid on config

I disabled armoredRavagerRaid as suggested, but the crash still happens. I really enjoy this mod, so as a temporary solution, I turned off the raid on server and created a datapack to obtain the Hero of the Village buff . Hopefully, we can find a better solution in the future. Thanks a lot for your help: )
