### ISSUE TITLE
Piglins ignore wither skeletons and zombified piglins when goety is installed

### ISSUE THREAD

**Issue by 305pence** [Polarice3/Goety-2#59]
Piglins normally run from zombified piglins and attack withers and wither skeletons, but they no longer do that if goety is installed (they will attack after they are attacked first however). 

they still hunt hoglins and run from soul fire though which is good

this is very niche and only bothers me because i'm trying to make a modpack where piglins fight pillager and wither skeleton factions

tested on version: goety-2.5.27.0.jar
forge version: 47.3.0

**Comment by Polarice3** [comment]
Will fix this pronto!

**Comment by Polarice3** [comment]
Fixed as of 2.5.27.1
