### ISSUE TITLE
[2.0.4] Dark Robe clips with outer skin layer

### ISSUE THREAD

**Issue by FyreAlchemage** [Polarice3/Goety-2#6]
Using version 2.0.4 for 1.19.2, when worn the dark robe clips with the outer skin layer, as shown here.
![image](https://user-images.githubusercontent.com/32804557/227755258-68a6fe91-4cc3-439b-b637-51a209e780c4.png)

**Comment by Polarice3** [comment]
Adjusted and fixed in 2.0.5!
