### ISSUE TITLE
c2me incompatibility / thread safety issue

### ISSUE THREAD

**Issue by tlitookilakin** [Polarice3/Goety-2#60]
Goety is currently incompatible with Concurrent Chunk Management engine. It crashes/errors trying to spawn an obsidian monolith during structure generation. It looks like the getLevel().random in this line is not thread-safe: https://github.com/Polarice3/Goety-2/blob/9d6215dfb3b2fc03ce4e56b62249574105bfd618/src/main/java/com/Polarice3/Goety/common/entities/neutral/AbstractMonolith.java#L84

[Crash log here](https://mclo.gs/YbEa8Xx), but it's not a clean install. I'll try to get a minimal reproduction later. I did not upload the full log because it's 76k lines long, but I can attach it if necessary.

**Comment by Polarice3** [comment]
I have no clue if this would fix this issue or not, but hopefully it does:
https://github.com/Polarice3/Goety-2/blob/ab572945245c68956279a03135164e3fa9865ae3/src/main/java/com/Polarice3/Goety/common/entities/neutral/AbstractMonolith.java#L84

**Comment by tlitookilakin** [comment]
Is that change included in 2.5.27.2?

**Comment by Polarice3** [comment]
Yes

**Comment by tlitookilakin** [comment]
Thanks! I'll give it a shot.

**Comment by tlitookilakin** [comment]
Works perfectly! Thanks a bunch.
